typography_spectrum: 0.4208881130338748
color:
  brandStrength: 0.23263925470264243
  lightness: 0.05643626044937732
  saturation: 0.4902560388863935
  rhythmicContrast: 0.1666870808979441
  brandColors:
    - '#FFFFFF'
    - '#400080'
    - '#FCE21C'
    - '#FF8000'
    - '#000000'
github: true
layout_spectrum: 0.24629565132652767
author:
  name: ''
  email: hesham@wah.by
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6bc29fdf-5ad2-4dee-91fd-97e7dc77fa13.gif
name: Hesham Wahby
url: 'http://share.hesham.wah.by'
navigation:
  - name: Games
    id: 4afa0937-28d9-4d1e-a663-1cd618ef4425
    type: content
  - name: About
    id: 405f1f8a-be99-49c9-b6b5-56fd57c0c325
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4441b43b-7e25-477a-b9c6-d380aa1f6dc7.gif
title: Hesham Wahby
content: []
description: ''
